---
format: pdf
---

# Nathan E. Rutenbeck

261 River Rd. Brooklin ME 04616 

+1.207.266.7198 | nathan@stonesetfarm.com | [LinkedIn](https://www.linkedin.com/in/nathan-rutenbeck/) | [GitHub](https://github.com/nerutenbeck)

### About

I'm a data scientist with ten years experience both in building and deploying machine learning models in a production environment, and in recruiting, training, and leading a team in model and pipeline development.  

I'm passionate about translating business objectives into data analytics pipelines and incorporating data analytics and uncertainty quantification into strategy and decision-making.

My technical expertise is in Bayesian learning, combining deep learning and Bayesian learning models, and uncertainty and risk quantification.

My industry background is carbon offsets and forest ecology and management, but I'm interested in positions across a wide range of fields related to green technology, energy, ESG finance and econometrics, climate change mitigation, environmental management, and AI ethics.

## Experience

### Data science

*Natural Capital Exchange (Jan 2018 - Dec 2022)*

- Piloted core development of continental-scale hybrid Bayesian / deep learning models of forest structure and disturbance
- Piloted core development of data engineering pipelines for model training and deployment
- Helped recruit, hire, train, and lead a world class team of data scientists and data engineers
- Served as senior team member guiding model and pipeline development to meet business goals
- Provided data science intelligence internally to support business strategy
- Assisted carbon offset methodology and program development

*Self employed statistical consultant (Nov 2015 - Dec 2017)*

- Conducted a project examining technology use in the classroom on global educational outcomes
- Conducted a project examining the influence of wind development on bird and bat populations

*Natural Capital Exchange (Jan 2014 - Nov 2015)*

- Led a team building software and tree- and forest-level machine learning models for remote-sensing assisted forest inventory projects
- Built MLOps pipelines to deploy inventory models
- Conducted remote sensing assisted forest inventory sample design, data collection, and processing
- Executed project operations, report development, and client communications

*Graduate Research Assistant, University of Maine (2013-2014)*

### Agriculture and forest management

*Yale School Forests, New Haven CT (2007 - 2008)*

*Stoneset Farm, Brooklin ME (2005 - 2012)*

*Horsepower Farm, Penobscot ME (2004 - 2005)*


## Skills and Knowledge

**statistical and machine learning, MLOps, decision theory, remote sensing and earth observation, carbon markets, forest biometrics, forest ecology and management, agriculture, social and environmental ethics**

### Tools

R, Python, bash, Stan, AWS, Azure, Docker, git, GitHub, Databricks, MLFlow, QGIS


## Education

**University of Maine (2012 - 2014)**
PhD, quantitative silviculture (unfinished)

**Yale School of the Environment (2010 - 2012)**
MF - Quantitative silviculture

**Yale Divinity School (2018 - 2012**
MAR - Social and environmental ethics

**Bard College**
Bachelor of Arts - Religion (1999 - 2003)


## Awards

- Doris Duke Conservation Fellowship, Doris Duke Foundation (2011)
- Irma Brandeis Award, Bard College (2003)
- Book Award, Bard College (2003)


## Peer-reviewed publications

- **Nathan E. Rutenbeck**, Brent R. Frey, Kristofer Covey, Graeme P. Berlyn, Oswald J. Schmitz, Bruce Conrad Larson, Mark S. Ashton. Influence of gap position and competition control on the leaf physiology of planted Picea glauca and natural regeneration of Populus tremuloides. Forest Ecology and Management.  2018 Sep 18.
